quarkus:
  default-locale: pt-BR
  datasource:
    db-kind: h2
    jdbc:
      url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=LEGACY"
  hibernate-orm:
    database:
      generation: drop-and-create
file-path: "Movielist.csv"